---

- hosts: lb_servers
  gather_facts: no
  sudo: yes
  tasks:
    # haproxy.cfg
    - copy: src=files/haproxy.cfg dest=/etc/haproxy/
      notify: haproxy restart
      tags: haproxy

    # keepalived.conf
    - template: src=files/keepalived.conf.j2 dest=/etc/keepalived/
      notify: keepalived restart
      tags: keepalived

    # rsyslog
    - copy: src=files/rsyslog.d/{{ item }} dest=/etc/rsyslog.d/
      notify: rsyslog restart
      tags:
        - haproxy
        - keepalived
      with_items:
        - haproxy.conf
        - keepalived.conf

    # logrotate
    - copy: src=files/logrotate.d/{{ item }} dest=/etc/logrotate.d/
      tags:
        - keepalived
      with_items:
        - keepalived

    # service started
    - service: name=haproxy state=started enabled=yes
      tags: haproxy

    - service: name=keepalived state=started enabled=yes
      tags: keepalived

  handlers:
    - name: rsyslog restart
      service: name=rsyslog state=restarted

    - name: haproxy restart
      service: name=haproxy state=restarted

    - name: keepalived restart
      service: name=keepalived state=restarted

- hosts: web_servers
  gather_facts: yes
  sudo: yes
  tasks:
    - copy: dest=/var/www/html/index.html content="{{ ansible_fqdn }}\n"

    - copy: dest=/var/www/html/ok.html content="OK\n"

    - copy:
        dest: /var/www/html/app.php
        content: |
          <?php
          session_start();
          header('Content-type: application/json');
          echo json_encode(array(
            'server' => php_uname('n'),
            'headers' => apache_request_headers(),
          ), JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
          echo PHP_EOL;

    - copy: dest=/var/www/html/app.css content="/* CSS */\n"
    - copy: dest=/var/www/html/app.js content="/* JavaScript */\n"

    - service: name=httpd state=started enabled=yes
